import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/app/components/SessionProvider'
import Navbar from './components/Navbar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <main className="mx-auto max-w-5xl min-h-screen p-24 flex gap-4">
            <Navbar />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
